spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: postgres
    password: A7med
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  mail:
#    host: ${EMAIL_HOSTNAME:default.smtp.gmail.com}
#    port: 465
#    username: ${EMAIL_USER_NAME}
#    password: ${EMAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          ssl.enable: true
#          ssl.trust: "*"
#    protocol: smtp

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/book-social-network"
application:
#  security:
#    jwt:
#      secret-key: iIJFqUaCgkXyrVFjk3VQDUgRxOJwRdKbAlD8cwlLWQNY4KmZUuqFuQwuXoKNWkcq
#      expiration: 8640000
#  mailing:
#    frontend:
#      activation-url: http://localhost:4200/activate_account
#  cors:
#    origins: http://localhost:4200, http://localhost:8080, http://192.168.0.227:8088, http://192.168.0.227:8080
  file:
    upload:
      photos-output-path: ./uploads
server:
  port: 8088

